title: Bloghore
description: Web edukasi dan blog seputar blockchain, crypto, dan web3
baseurl: "" # root domain
url: "https://bloghore.netlify.app/"     # ganti jika sudah ada domain

permalink: /:title/

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-polyglot
  - jekyll-archives
  - jekyll-admin

sass:
  sass_dir: _sass

paginate: 6
paginate_path: "/page:num"

languages: ["id", "en"]
default_lang: "id"

collections:
  posts:
    output: true
  authors:
    output: true
    permalink: /authors/:name/

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md

theme: minima
